import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{io}from'socket.io-client';import'./style.css';
const socket=io();
function App(){const [p,setP]=useState(null),[screen,setScreen]=useState('home'),[enemy,setEnemy]=useState(null),[status,setStatus]=useState('Онлайн');const id=window.Telegram?.WebApp?.initDataUnsafe?.user?.id||'demo_'+Math.floor(Math.random()*99999);const name=window.Telegram?.WebApp?.initDataUnsafe?.user?.first_name||'MILAS Player';
useEffect(()=>{window.Telegram?.WebApp?.ready();socket.on('player',setP);socket.on('match_found',x=>{setEnemy(x.enemy);setScreen('battle')});socket.on('presence',x=>{});socket.emit('login',{id,name});return()=>socket.disconnect()},[]);
if(!p)return <div className="loading">MILAS BRAWL<br/><small>Подключение к серверу…</small></div>;
return <div className="app"><header><b>MILAS <i>BRAWL</i></b><span>🪙 {p.coins}</span></header>{screen==='home'&&<main><section className="hero"><div className="logo">⚡</div><h1>ГОТОВ К БОЮ?</h1><p>Онлайн-арена прямо в Telegram</p><button className="play" onClick={()=>{setStatus('Ищем соперника…');socket.emit('queue')}}>ИГРАТЬ ОНЛАЙН</button><strong>{status}</strong></section><div className="stats"><div>🏆<b>{p.trophies}</b><small>Кубки</small></div><div>🪙<b>{p.coins}</b><small>Монеты</small></div><div>👤<b>{p.name}</b><small>Профиль</small></div></div><div className="menu"><button onClick={()=>setScreen('friends')}>👥 Друзья</button><button onClick={()=>setScreen('profile')}>👤 Профиль</button></div></main>}{screen==='friends'&&<Friends id={id} back={()=>setScreen('home')}/>} {screen==='profile'&&<main className="page"><button onClick={()=>setScreen('home')}>← Назад</button><h1>{p.name}</h1><p>🏆 {p.trophies} кубков</p><p>🪙 {p.coins} монет</p></main>}{screen==='battle'&&<Battle enemy={enemy} socket={socket} back={()=>setScreen('home')}/>}</div>}
function Friends({id,back}){const[f,setF]=useState([]);useEffect(()=>{fetch('/api/friends/'+id).then(r=>r.json()).then(setF)},[]);return <main className="page"><button onClick={back}>← Назад</button><h1>Друзья</h1>{f.length?f.map(x=><div className="friend" key={x.id}>{x.online?'🟢':'⚫'} {x.name}<span>{x.online?'В сети':'Не в сети'}</span></div>):<p>Пока нет друзей. Система друзей уже подключена к серверу.</p>}</main>}
function Battle({enemy,socket,back}){const[hp,setHp]=useState(100);const[ehp,setEhp]=useState(100);const[over,setOver]=useState(false);const hit=()=>{const n=Math.max(0,ehp-20);setEhp(n);socket.emit('attack',{damage:20});if(n===0){setOver(true);socket.emit('result',{win:true})}};useEffect(()=>{const fn=()=>setHp(x=>Math.max(0,x-20));socket.on('attack',fn);return()=>socket.off('attack',fn)},[]);return <main className="battle"><button onClick={back}>← Выйти</button><div className="arena"><div className="enemy">{enemy?.name||'Соперник'}<div className="bar"><span style={{width:ehp+'%'}}/></div>🤖</div><div className="center">⚔️<br/><small>{over?'ПОБЕДА!':'БОЙ ИДЁТ'}</small></div><div className="me">🦸<div className="bar"><span style={{width:hp+'%'}}/></div></div></div><button className="attack" disabled={over||hp<=0} onClick={hit}>⚡ АТАКА</button></main>}
createRoot(document.getElementById('root')).render(<App/>);
